# Generated by Django 3.1 on 2020-08-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduStatusTracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organization_authorization',
            new_name='Org_authorization',
        ),
        migrations.RenameModel(
            old_name='Organization_security_question',
            new_name='Org_security_question',
        ),
        migrations.RenameModel(
            old_name='Orgnization_user_verification',
            new_name='Org_user_verification',
        ),
    ]
