# Generated by Django 3.1 on 2020-08-12 12:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('EduStatusTracker', '0002_auto_20200812_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_authorization',
            name='orgAuthorizationId',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='org_security_question',
            name='orgSecurityQueID',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
