# Generated by Django 3.1 on 2020-08-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduStatusTracker', '0003_auto_20200812_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_user_verification',
            name='emailId',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
