# Generated by Django 3.1 on 2020-08-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduStatusTracker', '0004_org_user_verification_emailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_user_verification',
            name='emailId',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
